Repository Makstein/SnowbreakGachaExport, pull requests merged in 2024-07, with the labels that each got.

#17 chore(main): release 2.0.1
  CHANGELOG.md
Labels: autorelease: pending

#18 ci: trigger change
  .github/workflows/auto_merge.yml
  .github/workflows/dotnet.yml
Labels: autorelease: pending, automerge

#19 fix: wont create backup file when current history is empty
  .github/workflows/auto_merge.yml
  SnowbreakToolbox/Services/HistoryService.cs
Labels: automerge

#20 chore(main): release 2.0.2
  CHANGELOG.md
Labels: autorelease: pending

#21 ci: add workflow_dispatch and change include filter to exclude filter
  .github/workflows/dotnet.yml
Labels: automerge

#22 ci: syntax
  .github/workflows/dotnet.yml
Labels: automerge

#23 ci: syntax
  .github/workflows/dotnet.yml
Labels: automerge

#24 ci: enhance CI/CD
  .github/workflows/auto_merge.yml
  .github/workflows/dotnet.yml
Labels: automerge

#27 chore(main): release 2.1.0
  CHANGELOG.md
Labels: autorelease: pending

#28 fix: in 信源 part, after the result's been computed and displayed, chan…
  SnowbreakToolbox/Models/TetrisMapCell.cs
  SnowbreakToolbox/ViewModels/Pages/GachaHistoryViewModel.cs
Labels: automerge

#29 chore(main): release 2.1.1
  CHANGELOG.md
Labels: autorelease: pending

#30 fix: Import Gacha data func and Clear up history func
  SnowbreakToolbox/Services/HistoryService.cs
  SnowbreakToolbox/ViewModels/Pages/GachaHistoryViewModel.cs
Labels: automerge

#31 chore(main): release 2.1.2
  CHANGELOG.md
Labels: autorelease: pending
